version: "3"
services:
  tomcat-server-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - postgres-test
    ports:
      - "8383:8081"

  postgres-test:
    image: postgres:14.0-alpine
    volumes:
      - ./migrations//postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5430
    environment:
      POSTGRES_PASSWORD: postgres
