-- DDL
-------------------------------------------------------------------------------
-- Delete tables and sequences
-------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_LOJA CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_ENDERECO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_CONTATO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_RESPONSAVEL CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_PLANO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE T_IFD_ESPECIALIDADE CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_LOJA';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_ENDERECO';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_CONTATO';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_RESPONSAVEL';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_PLANO';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_IFD_ESPECIALIDADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;